//
// Created by bingo on 2019-11-16.
//

#ifndef ROSELIA_COMMON_TRANSPORT_CHANNEL_CHANNEL_PIPELINE_H_
#define ROSELIA_COMMON_TRANSPORT_CHANNEL_CHANNEL_PIPELINE_H_

class ChannelPipeline {

};

#endif //ROSELIA_COMMON_TRANSPORT_CHANNEL_CHANNEL_PIPELINE_H_
